USE master;
GO

IF DB_ID(N'ReolmarkedetDB') IS NULL
BEGIN
    EXEC(N'CREATE DATABASE ReolmarkedetDB');
END;
GO

USE ReolmarkedetDB;
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;


CREATE TABLE dbo.TENANT (
	TenantID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(20) NULL,
	Email NVARCHAR(255) NULL,
	IsActive BIT NOT NULL
		CONSTRAINT DF_TENANT_IsActive DEFAULT (1)
	);

CREATE TABLE dbo.SHELFTYPE (
	ShelfTypeID INT PRIMARY KEY IDENTITY(1,1),
	ShelfTypeName NVARCHAR(50) NOT NULL,
		CONSTRAINT UQ_SHELFTYPE_ShelfTypeName UNIQUE (ShelfTypeName)		
	);

CREATE TABLE dbo.SHELF (
	ShelfID INT PRIMARY KEY IDENTITY(1,1),
	ShelfNumber INT NOT NULL,
	IsActive BIT NOT NULL
		CONSTRAINT DF_SHELF_IsActive DEFAULT (1),
	ShelfTypeID INT NOT NULL,

		CONSTRAINT UQ_SHELF_ShelfNumber UNIQUE (ShelfNumber),
		CONSTRAINT CK_SHELF_ShelfNumber_Positive CHECK (ShelfNumber > 0),
		CONSTRAINT FK_SHELF_SHELFTYPE
			FOREIGN KEY (ShelfTypeID) REFERENCES dbo.SHELFTYPE(ShelfTypeID)
	);

CREATE TABLE dbo.RENTAL (
	RentalID INT PRIMARY KEY IDENTITY(1,1),
	StartDate DATE NOT NULL,
	MonthlyRent DECIMAL(10, 2) NOT NULL CHECK (MonthlyRent >= 0),
	EndDate DATE NULL, 
	TerminationNoticeDate DATE NULL,
	TenantID INT NOT NULL,
	ShelfID INT NOT NULL,
		CONSTRAINT FK_RENTAL_TENANT
			FOREIGN KEY (TenantID) REFERENCES dbo.TENANT(TenantID),
		CONSTRAINT FK_RENTAL_SHELF 
			FOREIGN KEY (ShelfID) REFERENCES dbo.SHELF(ShelfID),
		CONSTRAINT CK_RENTAL_EndDate
			CHECK (EndDate IS NULL OR EndDate > StartDate)
	);

CREATE TABLE dbo.ITEM (
	ItemID INT PRIMARY KEY IDENTITY(1,1),
	Description NVARCHAR(255) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL CHECK (Price >= 0),
	Barcode NVARCHAR(50) NOT NULL UNIQUE,
	RentalID INT NOT NULL,
		CONSTRAINT FK_ITEM_RENTAL
		FOREIGN KEY (RentalID) REFERENCES dbo.RENTAL(RentalID)
	);

CREATE TABLE dbo.SALE (
	SaleID INT PRIMARY KEY IDENTITY(1,1),
	SaleDate DATE NOT NULL,
	SalePrice DECIMAL(10, 2) NOT NULL CHECK (SalePrice >= 0),
	Notes NVARCHAR(500) NULL,
	ItemID INT NOT NULL UNIQUE, 
		CONSTRAINT FK_SALE_ITEM
			FOREIGN KEY (ItemID) REFERENCES dbo.ITEM(ItemID)
	);

COMMIT TRANSACTION;
GO


