USE ReolmarkedetDB;
GO

IF COL_LENGTH('dbo.RENTAL', 'IsCustomPrice') IS NULL
BEGIN
    ALTER TABLE dbo.RENTAL
    ADD IsCustomPrice BIT NOT NULL
        CONSTRAINT DF_RENTAL_IsCustomPrice DEFAULT (1)
        WITH VALUES;
END;
GO

ALTER TABLE dbo.RENTAL
DROP CONSTRAINT DF_RENTAL_IsCustomPrice;

ALTER TABLE dbo.RENTAL
ADD CONSTRAINT DF_RENTAL_IsCustomPrice
    DEFAULT (0) FOR IsCustomPrice;
GO